# version: '3.8' (obsolete, removed as per warning)

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    volumes:
      - nextcloud_postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - nextcloud_network

  redis:
    image: redis:${REDIS_VERSION}
    restart: always
    volumes:
      - nextcloud_redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb
    networks:
      - nextcloud_network

  nextcloud:
    image: nextcloud:${NEXTCLOUD_VERSION}
    restart: always
    depends_on:
      - postgres
      - redis
    volumes:
      - nextcloud_data:/var/www/html
      - ./nextcloud/config:/var/www/html/config
    environment:
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${SERVER_IP}:${HTTPS_PORT}
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=redis
      - APACHE_DISABLE_REWRITE_IP_RULES=1
    networks:
      - nextcloud_network

  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - nextcloud
    ports:
      - "${HTTPS_PORT}:8443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/nextcloud.crt:/etc/ssl/certs/nextcloud.crt
      - ./nginx/ssl/nextcloud.key:/etc/ssl/private/nextcloud.key
      - nextcloud_data:/var/www/html:ro
    networks:
      - nextcloud_network

volumes:
  nextcloud_data:
  nextcloud_postgres_data:
  nextcloud_redis_data:

networks:
  nextcloud_network:
    driver: bridge